### ISSUE TITLE
Caching for reflection

### ISSUE THREAD

**Issue by MrWormHole** [devfeel/mapper#11]
Question: Do we do caching to not repeat reflection for each mapper call for structs?

**Comment by devfeel** [comment]
I can't find a effective method to caching for reflection with golang, do you know some methods?

**Comment by MrWormHole** [comment]
Cool, I will think to come up with a draft PR

**Comment by devfeel** [comment]
Looking forward！

**Comment by shyandsy** [comment]
@MrWormHole any proposal for the caching reflection?

**Comment by MrWormHole** [comment]
Hi @shyandsy I have tried but it didn't go well. The purpose was to not call reflection between the same 2 structs more than once

**Comment by shyandsy** [comment]
could you please submit a PR? and I will tale a look laterwe may find an solution for that发自我的华为手机-------- 原始邮件 --------发件人： Talha Altınel ***@***.***>日期： 2021年11月29日周一 17:35收件人： devfeel/mapper ***@***.***>抄送： shyandsy ***@***.***>, Mention ***@***.***>主    题： Re: [devfeel/mapper] Caching for reflection (#11)
Hi @shyandsy I have tried but it didn't go well. The purpose was to not call reflection between the same 2 structs more than once

**Comment by shyandsy** [comment]
> Hi @shyandsy I have tried but it didn't go well. The purpose was to not call reflection between the same 2 structs more than once

could you please submit a PR to show the principle concept? I will try to help

**Comment by MrWormHole** [comment]
Actually the problem was trying to reduce the reflection which is done during the mapping operation, we can not do caching because there could be different requests in a http server which are using the map function, and the same request will less likely to be callling the map function more than one time with the same data.

The easiest solution was to write a basic codegen for me. I did write mapperx as a repo. It is much like the same thing with json marshalling, we can not really cache it but we can code generate it for its respective types. Example is ffjson.
