### ISSUE TITLE
这种情况怎么转？

### ISSUE THREAD

**Issue by Wsyspringsun** [devfeel/mapper#13]
type Temp struct {
	ObjectId int64  `json:"objectId" form:"objectId" gorm:"primaryKey;column:object_id;comment:base-主键;type:bigint"`
	Name     string `json:"name" form:"name" gorm:"column:name;comment:名称;"`
	Value    int64  `json:"value" form:"value" gorm:"column:value;comment:值;"`
}

val := []model.Temp{
		model.Temp{1, "1", 11},
		model.Temp{2, "2", 12},
		model.Temp{3, "3", 13},
	}
	m := model.Data{
		TblName: "test",
		Data:    val,
	}
	bytes, _ := json.Marshal(m)

	n := new(model.Data)
	err := json.Unmarshal(bytes, n)
	if err != nil {
		t.Fatal(err)
	}

	arr := make([]model.Temp, 0)
	mapper.Register(&model.Temp{})
	if err := mapper.MapperSlice(n.Data, arr); err != nil {
		fmt.Println(arr)
	} else {
		t.Error("错误")
	}

**Comment by shyandsy** [comment]
could you please reformat you issue first?

and provide a piece runnable code please

```go
model.Data. // where is the defination of the Data struct
```

here is a document about how to use markdown
> https://zhuanlan.zhihu.com/p/108984311
