### ISSUE TITLE
Can support customized tag be used for structure conversion? // 能不能自定义转换用的tag

### ISSUE THREAD

**Issue by XC-Zero** [devfeel/mapper#34]
现有结构体里有其他 `tag` 比如 `bson` `form` 或其他 `自定义标签` ,能否`自定义标签`用于结构体转换呢?

**Comment by devfeel** [comment]
接受建议，将于下个版本实现，为了防止不必要的逻辑误导，考虑“显示”启用生效设置及相应的标签Flag设置
