### ISSUE TITLE
IMapper是并发安全的吗

### ISSUE THREAD

**Issue by lookno** [devfeel/mapper#38]
IMapper是并发安全的吗，服务全局持有一个就可以，还是每次请求都需要NewMapper?

**Comment by devfeel** [comment]
是的，Mapper本身只存储两个数据（fieldNameMap，registerMap），用得也是sync.Map，除此之外都是无状态的，所以操作都是并发安全的，在没有特殊需求（如动态改变mapper的一些配置）情况下，可以复用一个全局Mapper
