### ISSUE TITLE
Mapper doesn't work on composition

### ISSUE THREAD

**Issue by naeemaei** [devfeel/mapper#39]
I have this models that wants to map a slice of `Country` to a slice of `CountryRes`

Source:

```
// Base model
type BaseModel struct {
	Id    int    `json:"id"`
}

// Country model
type Country struct {
	BaseModel
	Name string `json:"name"`
}

//
type CountryRes struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}
```

When I want to map a slice of `Country` to a slice of `CountryRes` the `Id` field has been ignored.

```
var items *[]Country = new([]Country)
var mitems *[]CountryRes = new([]CountryRes)
err = mapper.MapperSlice(items, mitems) 
```

The execution didn't have any errors but the `Id` field had been ignored.

**Comment by devfeel** [comment]
I get it. Due to the inability to automatically recognize the fields of composition, they have been ignored. I am considering adding special tags to further facilitate the conversion.

**Comment by devfeel** [comment]
You can try it with version 0.7.13

**Comment by devfeel** [comment]
Use code: https://github.com/devfeel/mapper/blob/master/example/object/main.go
