### ISSUE TITLE
Can not map an an aray of struct to another

### ISSUE THREAD

**Issue by ajitchahal** [devfeel/mapper#6]
I am trying to map an array of struct to another array.
`package main

import (
	"fmt"

	"github.com/devfeel/mapper"
)

type Emp struct {
	Name  string
	Class int
}
type Emp2 struct {
	FirstName string `mapper:"Name"`
	Class     int
}

func main() {
	e1 := Emp{Name: "Ajit", Class: 1}

	var e2 Emp2
	if err := mapper.Mapper(&e1, &e2); err != nil {
		fmt.Println(err)
	}
	fmt.Printf("e1:= %v", e1)
	fmt.Printf("e2:= %v", e2)
	e2 = Emp2{}
	a1 := []Emp{
		Emp{Name: "Ajit", Class: 1},
		Emp{Name: "vinit", Class: 2},
	}
	var a2 []Emp
	if err := mapper.Mapper(&a1, &a2); err != nil {
		fmt.Println(err)
	}
	fmt.Printf("a1:= %v", a1)
	fmt.Printf("a2:= %v", a2)
}`

But it results in panic
`7:31:44 app         | panic: reflect: call of reflect.Value.NumField on slice Value

goroutine 1 [running]:
reflect.flag.mustBe(...)
        /usr/local/Cellar/go/1.13.1/libexec/src/reflect/value.go:208
reflect.Value.NumField(0x10cdba0, 0xc00000c080, 0x197, 0x11194e0)
        /usr/local/Cellar/go/1.13.1/libexec/src/reflect/value.go:
7:31:44 app         | 1356 +0xbe
github.com/devfeel/mapper.registerValue(0x10cdba0, 0xc00000c080, 0x197, 0x1044900, 0x1055610)
        /Users/d069900/go/src/github.com/devfeel/mapper/mapper.go:116 +0x30f
github.com/devfeel/mapper.elemMapper(0x10cdba0, 0xc00000c080
7:31:44 app         | , 0x197, 0x10cdba0, 0xc00000c0a0, 0x197, 0xd, 0x10)
        /Users/d069900/go/src/github.com/devfeel/mapper/mapper.go:299 +0xbb2
github.com/devfeel/mapper.Mapper(0x10c9880, 0xc00000c080, 0x10c9880, 0xc00000c0a0
7:31:44 app         | , 0xc000084ef0, 0x1)
        /Users/d069900/go/src/github.com/devfeel/mapper/mapper.go:254 +0x1c1
main.main()
        /Users/d069900/rnd/go/go-school/src/object-mappers/main.go:33 +0x369
`

Issue 1: it must only return error and not panic
issue 2: arrays are not mapped

**Comment by devfeel** [comment]
ok，I have recorded the issue. I will solve it on next version. thank you.

**Comment by devfeel** [comment]
now support slice's element type in ptr or struct when use MapperSlice\MapperMapSlice. you can try it.
about test code in  mapper_test.go:Test_MapperSlice\Test_MapperStructSlice\Test_MapperMapSlice\Test_MapperStructMapSlice
