### ISSUE TITLE
[BUG] MapperSlice panics while mapping from *[] to *[]

### ISSUE THREAD

**Issue by MrWormHole** [devfeel/mapper#8]
if i have two different structs, i can not use both of their pointers in MapperSlice function.

this works 
mapper.MapperSlice(highscores, &highscoresResponse)

this doesn't work and panics in the runtime(this should be supported in my opinion)
mapper.MapperSlice(&highscores, &highscoresResponse)

this doesn't work obviously which is normal(source code states toElem has to be pointer)
mapper.MapperSlice(highscores, highscoresResponse)

There should be a mechanism to improve for the second option. Should i open a PR for this?

**Comment by devfeel** [comment]
can you take example for use MapperSlice code?

**Comment by devfeel** [comment]
Now is supported on version 0.7.5
